### ISSUE TITLE
Metrics for BTP Manager via Victoria Metrics setup

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#261]
**Description**

We'd like to see how the BTP manager instances work across all SKRs. 

**AC**
- [x] 0) Get knowledge of how we can see metrics from the BTP Manager module for every SKR
- [x] 1) Design metrics for BTPOperator
  - [x] a) Design go metrics
  - [x] b) Design business metrics
  - [x] c) Discuss metrics with the team
- [x] 2) MVP implementation has metrics like BTP Operator status
  - [x] 2.1) Implement grafana views too  
- [ ] 3) ~~Document metrics in the btp-manager~~

**Comment by ralikio** [comment]
Ideas on what to monitor:
* BTP Manager Cert regenerations.

**Comment by ralikio** [comment]
TODO: 
- [ ] Check "Runtime Metrics"

**Comment by ralikio** [comment]
The following comment summarises our findings on what to monitor to get useful insights about BTP Manager and its BTP Operator. 

Main Mechanics:
- [ ] Metrics for specific POD
- [ ] Metrics for specific SRK
- [ ] Landscape for all metrics from 

Metrics ideas:
- [ ] ConfigMaps Modifications - monitor changes of ConfigMap that stores configuration for a BTP Manager, check existence of the map. Number of events that designate secrets modifications.
- [ ] Reconciliation Time - histogram with percentile for reconciliation time, check if this can be done with standard metrics for controller_runtime_* from kubebuilder.
- [ ] Reconciliation Invocation - metrics for verification of reconciliation invocations, that is how many times reconciliation of BTP Operator happened. Has the reonciliation even occur? What happens when there is no reconciliation? Make distinction between case where there is no module manager and second case where there is no BTP Operator CRD. Send metrics only when reconciliations is expected.Check if we can combine metric about resource existence and reconciliation count.
- [ ] Instance/Bindings Number - histogram with service instance/bindings number, e.g.100 cluster have 0 instances, on 30 instances 10, on 20 1 itp.
- [ ] Applied Resources - count resourcesToApply invocations, mainly for logging resources, go routine invocations -  in the method we are invocing as many go routines as there are resources to apply (see resourcesToApply and resourcesToApply).
- [ ] Memory - memory metrics for both operator and manager.
- [ ] Error States - some kind of a metric (aggregation of rules) that tells if specific cluster is in the error state
- [ ] Error States SKR Summary - metric that tells what number of SKR clusters are in error state, initial metrics should show only currently unfixed bugs - current errors state.
- [ ] CRDS Count - how many CRDS of btp-operators are there - call to Kubernetes API
- [ ] Force Delete Count - number of manager instances with BtpOperator CRD labeled by "force-delete"- the metric tells if there were any external modifications done to the resource
- [ ] Routines Count - Go Routine Start/Finish
- [ ] Hard/Soft Removal - number of soft-delete/hard-delete operations - tells how many times finalizers were removed
- [ ] Certs Regenerations - BTP Manager Cert regenerations.
- [ ] Version - what is the current version of BTP Manager?
- [ ] Redundant BTP Operator Resources - There is a method called HandleRedundantCR in BTP Manager that is invoked when there are more than one BTP Operator CRD. Check how many clusters, which have more than one CR, are there.
	
Additionally, we have discussed key points and practices that we want to remember about while implementing the metrics:
	• Kubebuilder metrics for both of our managers, main one and the helper
	• For how long a metric stays in Grafana and if RMA removes shoots from Grafana for removed runtimes.
	• Lets keep meeting!
	• Filtrowanie po shootach, typie error (zeby dostac liczbe klastrów afektowanych przez blad),
	• Do not make external calls, e.g. do not call K8S api to check Kyma Resource
	• Use Colors for Metrics so that we can quickly see that we need to do something
	• rozroznienie czy metryka wskazuje blad czy tylko daje jakies dodatkowe informacji o dobrym ale innym stanie klastra
	• Lets be descriptive

**Comment by ralikio** [comment]
test for @ukff

**Comment by ralikio** [comment]
test for @ukff
