### ISSUE TITLE
Remove usage of the kyma CLI modules functionality from btp-manager

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#522]
In the recent approach the creation of component-descriptor (OCI module image) is handled by submission pipeline in `module-manifests` directory.
The image is created by invocations of `kyma CLI`.
Then the image is pushed to [https://europe-docker.pkg.dev/kyma-project/modules-internal](https://europe-docker.pkg.dev/kyma-project/modules-internal)

We provide (in the latests promotion workflow) all information needed to create appropriate component-descriptor.

But in our release workflow we still create component-descriptor "the old way" calling `kyma CLI` from our Makefile.

AC:
[ ] - remove prow job: "pull-btp-manager-module-build" which is using kyma cli from btp-manager make file
[ ] - we are able to run e2e tests during our release process (rewrite test to not use scopeo etc, just use renderd.yaml to install btp-manager)
[ ] - remove [template.yaml](https://github.com/kyma-project/btp-manager/releases/download/1.0.2/template.yaml) and [template_control_plane.yaml](https://github.com/kyma-project/btp-manager/releases/download/1.0.2/template_control_plane.yaml) from new releases
[ ] - security scans are configured for main, release candidate (latest release) and the release channels (regular, fast)

**Comment by jaroslaw-pieszka** [comment]
WIP: https://github.com/kyma-project/btp-manager/pull/550
- [x] E2E tests invoking `make` instead of `kyma CLI`.
- [x] E2E upgrade tests invoking `make` instead of `kyma CLI` and fetching base manifest from release artifacts.
- [  ] release workflow uploads manifest created by `make` invocations
- [  ] template files not generated any more in release process
