### ISSUE TITLE
Activate BTP Manager in the SKR where btp-operator is present

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#69]
**Description**

We need to ensure that for a short period (2 days) of time both Reconciler and BTP Manager will reconcile BTP Operator chart without issues.

**AC**
- make sure that BTP Manager and Reconciler BTP operator are in the same chart version
- check if BTP Manager will work properly in the existing cluster. Create a BtpOperator instance, it should succeed.
- check if Reconciler and BTP-Manager reconciliations do not harm each other
- BTP Manager enabled in the SKR, then remove it from KYMA CR and check what happened in the cluster. We expected Manager to be uninstalled but what about btp-operator resources? Document results under this issue.

**Comment by ralikio** [comment]
Test Scenario:

1. Create an SKR and wait till created.
1. TODO: Create a service instance
3. Install all prerequisites for the BTP Manager.
	Results: Secrets are already in place
4. Check status of BTP Operator.
5. Check status of the service instance
5. Run the BTP Manager locally.
6. Create an operator resource.
7. Check status of the BTP Operator.
7. Check status of the service instance
8. Wait on the next reconciliation.
9. Remove operator resource.
10. Wait on the next reconciliation.
11. A new BTP Operator instance is recreated.
12. Create a fresh service instance: result - in progress for a long time

**Comment by ralikio** [comment]
During testing we have discovered some minor issues that do not prevent migration. The issue is that both BTP Manager and BTP Operator Reconciler compete with each other to update the same BTP Operator component. The updates should occur only when version of BTP Operator managed by Reconciler and Operator differ from each other (for example by having different BTP Operator version). In case differences are detected and the BTP Operator is updated our rolling update strategy keeps operator pods running, keeping BTP Operator up and operational. Migration should not cause any issues in the described area.


Revisited AC:

AC
- ~make sure that BTP Manager and Reconciler BTP operator are in the same chart version~ - It was not necessary because we checked the worst case scenario that is when versions are different and overwrites happen. The case does not prevent BTP Operator from doing its work.
- check if BTP Manager will work properly in the existing cluster. Create a BtpOperator instance, it should succeed - Done, BTP Manager works properly, that is it reconciled the Operator to correct `Ready` state.
- ~check if Reconciler and BTP-Manager reconciliations do not harm each other~ - as described above we have rolling update strategy that prevents outage of the Operator.
- BTP Manager enabled in the SKR, then remove it from KYMA CR and check what happened in the cluster. We expected Manager to be uninstalled but what about btp-operator resources? Document results under this issue. - not done.
